name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/upload-cloud-storage@main
        with:
          path: .
          destination: ${{secrets.BUCKET_NAME}}
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: |
          ls
